### ISSUE TITLE
[cloud-run-hello-csharp]: Guide needs to be updated for latest .NET

### ISSUE THREAD

**Issue by thatislg** [googlecodelabs/feedback#1273]
Dotnet version was updated in GCP Cloud Shell. and this guide can not use

**Comment by meteatamel** [comment]
@thatislg thanks for reporting this. It's fixed now, please try again and let us know if you run into issues: 
https://codelabs.developers.google.com/codelabs/cloud-run-hello-csharp

**Comment by thatislg** [comment]
> @thatislg thanks for reporting this. It's fixed now, please try again and let us know if you run into issues: 
> 
> https://codelabs.developers.google.com/codelabs/cloud-run-hello-csharp

thks for your reply. 
I will check this tutorial again.
If i still get the problem, i will report on this flow.
